### ISSUE TITLE
Feature Request: Return all possible strings, rather than only one?

### ISSUE THREAD

**Issue by AD-Wright** [DataPools/FriendlySeeds#1]
Hello!  This is a great project, and your tool works really well.

I am curious if this can be used to "reverse" numeric seeds to find the original word.  As I understand, the hashing process means there are several different "words" that can result in the same seed.  For example, `DataPools` and `Bej\ATCH` both result in the same numerical seed, `1626596909`.  Can your map of possible options be used to return all possible strings?  It is possible that some of the strings may be easier to remember than others.  

I am not familiar enough with JavaScript to see for myself if that is possible.  It may not be.  Thank you in advance.

**Comment by DataPools** [comment]
The issue is finding all possible collisions. FriendlySeeds takes advantage of a collision flaw in String.hashCode() and displays the first one it finds. Finding all collisions would require an extremely slow brute-force search. 

I have tested some brute-force code myself and it takes around ~5 minutes to reverse a seed and they usually aren't any more readable.

**Comment by AD-Wright** [comment]
Interesting.  Do you have the brute-force code published anywhere? I understand if including this feature in this repository is out of scope.

**Comment by DataPools** [comment]
I don't have the exact code I used, but I just now managed to cobble together brute-force code from this project. This code is very similar to what I used back when I tested the brute-force approach:

```
//The seed to reverse
var seed = 71;
console.log("Bruteforce for seed: " + seed);
//This is the 'A' char
var minValue = 65;
//This is the 'z' char
var maxValue = 122;
bruteforceSeed(seed);

function bruteforceSeed(seed) {
    //Search all possible strings from length 1 to maxWordLen
    var maxWordLen = 25;
    for (var j = 1; j <= maxWordLen; j++) {
        var arr = new Array(j);
        for (var i = 0; i < arr.length - 1; i++) {
            arr[i] = String.fromCharCode(minValue);
        }
        arr[arr.length - 1] = String.fromCharCode(minValue - 1);
        while (increment(arr)) {
            var hash = hashCode(arr);
            if (hash == seed) {
                console.log(arr.join(''));
            }
        }
    }
    console.log("Finished looking through seeds of length "+maxWordLen);
}


function increment(arr) {
    if (arr[0].charCodeAt(0) > maxValue) {
        return false;
    }
    arr[arr.length - 1] = nextChar(arr[arr.length - 1]);
    for (var i = arr.length - 1; i > 0; i--) {
        if (arr[i].charCodeAt(0) > maxValue) {
            arr[i] = String.fromCharCode(minValue);
            if (i > 0) {
                arr[i - 1] = nextChar(arr[i - 1]);
            }
        }
    }
    return arr[0].charCodeAt(0) <= maxValue;
}

function nextChar(c) {
    return String.fromCharCode(c.charCodeAt(0) + 1);
}

function hashCode(value) {
    var h = 0;
    if (value.length > 0) {
        for (var i = 0; i < value.length; i++) {
            {
                h = 31 * h + (function(c) {
                    return c.charCodeAt == null ? c : c.charCodeAt(0);
                })(value[i]);
                //The "| 0" is needed to simulate 32 bit integer overflow that Java ints have
                h = h | 0;
            }
        }
    }
    return h;
}
```

**Comment by AD-Wright** [comment]
Wow! Thank you!
